### ISSUE TITLE
Code refactor - Part I

### ISSUE THREAD

**Issue by MariaEduardaDeAzevedo** [MariaEduardaDeAzevedo/ZoIA#2]
# Task description
Code refactor focused on directory structure refactoring as MVC pattern. 
- Use SQL Alchemy and Marshmallow instead Psycopg2
- Use Flask API instead just Flask Framework 

# Acceptance criteria 
- [ ] Directories structure refactoring as MVC
- [ ] SQL Alchemy integration
- [ ] Flask API integration
