### ISSUE TITLE
Integrate the en-pt translation model

### ISSUE THREAD

**Issue by MariaEduardaDeAzevedo** [MariaEduardaDeAzevedo/ZoIA#5]
# Task description

Integrate a translation model to translate the inferences to portuguese. 

> Analyse the Unicamp model available on HuggingFace: https://huggingface.co/unicamp-dl/translation-en-pt-t5

# Acceptance criteria

- [ ] Integrate the model on the application pipeline
    - [ ] Explore the model using a Google Colab
    - [ ] Download and integrate
    - [ ] Implement the change language feature on the frontend
